version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: <command>
  backend_test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: rake
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - backend_test
