version: 2
jobs:
  build:
    working_directory: ~/business-period
    docker:
      - image: circleci/ruby:2.4.1
      environment:
        RAILS_ENV: test
  steps:
    - checkout

    - run: bundle exec rake
